### ISSUE TITLE
[API] Add a system to make tables available again

### ISSUE THREAD

**Issue by ekaulfuss** [Rapid-Reservation/rapid-api#14]
### Acceptance Critera:
Discuss following ssuggestions and decide on plan of action: 

1. One hour after seating,  have them automatically switch back 
2. Create an endpoint that can be hit to reset the tables

**Comment by HaffCaff** [comment]
I was thinking about this, like having a reset endpoint or a query that will re-seed database to its default setting. I think its a good idea and something we should discuss with @luketwainwright and @dcamp27 !

**Comment by HaffCaff** [comment]
@ekaulfuss or @luketwainwright 

Did you guys want to prototype this out and possibly have something ready by Thursday?

**Comment by dcamp27** [comment]
The database does store the time that the order is placed so we could do something like that plus 120 minutes to trigger the change.
