### ISSUE TITLE
[API] Start /customer endpoints

### ISSUE THREAD

**Issue by HaffCaff** [Rapid-Reservation/rapid-api#15]
### Acceptance Criteria: 

- Correct endpoints from to retrieve all relevant data about an order
     - [ ] GET all customers
     - [ ] GET customer by id
     - [ ] POST create new customer

**Comment by luketwainwright** [comment]
I was looking at the SRS and do we need to work on an addCusotmer, editCustomer, deleteCustomer and searchCusotmer endpoint for now?

**Comment by HaffCaff** [comment]
@luketwainwright Correct!

**Comment by HaffCaff** [comment]
Closed by @ekaulfuss  contribution to https://github.com/Rapid-Reservation/rapid-api/commit/8e7b0e0532c9dd05b8fcf1090aa2cbcec9b9497c

@ekaulfuss individual commit here: https://github.com/Rapid-Reservation/rapid-api/commit/5c2621718a5bee1272c60f8d4035408c5fdb077e

Individual contribution was rolled into mega update, all work was Edison's regarding the /customer endpoint
