### ISSUE TITLE
[API] Research possibly using REDIS as cache instead of current API cache

### ISSUE THREAD

**Issue by HaffCaff** [Rapid-Reservation/rapid-api#16]

**Comment by luketwainwright** [comment]
Research on integrating REDIS into our API. Here's what I found:

- REDIS is an in-memory data structure store

- Reduces the need to fetch data every time

- Can handle large volumes of data and concurrent requests. 

- Works best if deployed using Linux but can still be utilized on Windows, macOS, etc.

- REDIS improves scalability and performance by: 
- caches frequently accessed data 
- thereby, reducing the number of database queries 
- with that, it eases the load on the database

Overall, adding REDIS will definitely improve caching performance. In theory, this web app will not experience large volumes of data considering its a school project. However, it will be beneficial to incorporate, to get experience using this software for real world applications that will handle large volumes of data. Also, no matter what, we want the best performing software when developing any application.

**Comment by HaffCaff** [comment]
Thanks for the info @luketwainwright! Currently, we have caching in the API but it's time based. So every 60 seconds, the local cache clears. My thoughts were to possibly leverage redis so that when a query is made, mainly `GET /tables`, the  key value store of redis will hold the state UNLESS there is a change. With our current implementation of caching, its 60 seconds, regardless if there was a change. I was thinking this might help with potential race condition problems down the road! 

This might be slight overkill, but showing off a performant API is a great thing for portfolios!
