### ISSUE TITLE
[API] Test endpoints after database updates

### ISSUE THREAD

**Issue by HaffCaff** [Rapid-Reservation/rapid-api#9]
### Acceptance Criteria:

- [x] All queries are adjusted to fit new DB schema
     - [x] `INSERT RESERVATION`
     - [x] `SELECT_RESERVATION`
     - [x] `GET_TABLE_INFO`
- [x] All Endpoints can be hit and return correct data
     - [x] `GET /table`
     - [x] `POST /table`
     - [x] `GET /table/<int:table_number>`

**Comment by HaffCaff** [comment]
I took care of the `GET /table` endpoint and query for work on https://github.com/Rapid-Reservation/rapid-ui/issues/5

**Comment by ekaulfuss** [comment]
INSERT_RESERVATION and the POST /table were updated
